from graphs.use_cases.matrix_use_cases.CreateMatrixGraphUseCase import CreateMatrixGraphUseCase
from graphs.use_cases.matrix_use_cases.CreateMatrixGraphUseCase2 import CreateMatrixGraphUseCase2
from graphs.use_cases.adjacency_structure_use_cases.CreateAdjacencyGraphUseCase import CreateAdjacencyGraphUseCase
from graphs.use_cases.adjacency_structure_use_cases.CreateAdjacencyGraphUseCase2 import CreateAdjacencyGraphUseCase2

use_case_01 = CreateMatrixGraphUseCase()
use_case_02 = CreateMatrixGraphUseCase2()
use_case_03 = CreateAdjacencyGraphUseCase()
use_case_04 = CreateAdjacencyGraphUseCase2()
