from graphs.use_cases.matrix_use_cases.CreateMatrixGraphUseCase import CreateMatrixGraphUseCase
from graphs.use_cases.matrix_use_cases.CreateMatrixGraphUseCase2 import CreateMatrixGraphUseCase2

use_case_01 = CreateMatrixGraphUseCase()
use_case_02 = CreateMatrixGraphUseCase2()
